### ISSUE TITLE
Every command fails with "ENOENT: spawn command ENOENT"

### ISSUE THREAD

**Issue by waiting-for-dev** [heroku/heroku-pg-extras#129]
Hi,

every command run results in following output:

    ENOENT: spawn command ENOENT

For example:

    > heroku pg:calls -r production       
    ▸    ENOENT: spawn command ENOENT

Some debugging information:

```
> heroku plugins
=== Installed Plugins
heroku-pg-extras@1.0.3
```

```
> ruby --version
ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]
```

Many thanks

**Comment by uhoh-itsmaciek** [comment]
Hi, thanks for reporting the issue. Do you have `psql` installed? What's the output of `heroku version` and what OS and version are you running?

/cc @dickeyxxx

**Comment by waiting-for-dev** [comment]
Hey, thanks for the support.

Yes, `psql` is installed.

```
> heroku version
heroku-toolbelt/3.43.7 (x86_64-linux-gnu) ruby/2.1.5
heroku-cli/5.2.34-65b16c9 (linux-amd64) go1.6.2
=== Installed Plugins
heroku-pg-extras@1.0.3
```

My operating system is a Debian 8 container running within Qubes OS.

Thanks!

**Comment by uhoh-itsmaciek** [comment]
Ok, I was able to reproduce on Ubuntu 16.04--we made some changes here recently and I suspect this is related. We'll follow up once we know more.

**Comment by aaron-coolfront** [comment]
Experiencing the same thing on Ubuntu 12.04 as a VM in VirtualBox as well.

`heroku-toolbelt/3.42.44 (x86_64-linux) ruby/1.9.3
heroku-cli/5.2.34-65b16c9 (linux-amd64) go1.6.2
=== Installed Plugins
heroku-pg-extras
heroku-pg-extras@1.0.3
heroku-redis@1.2.7
heroku-vim
heroku-vim@1.0.1
`

**Comment by uhoh-itsmaciek** [comment]
Thanks for the additional info @aaron-coolfront. We've tracked down the issue to our usage of `command` on Linux and are working on a fix. It should be out in a couple of days--sorry about the inconvenience.

**Comment by waiting-for-dev** [comment]
Thanks for the quick fix. Now it's working. Cheers.

**Comment by danielcapello** [comment]
Hi, I´m using Qubes OS too @waiting-for-dev . I want to ask: Everytime when I shutdown my AppVM, heroku is uninstalled. Is it happens to you too? What I need to do?

**Comment by waiting-for-dev** [comment]
@danielcapello , surely you are installing it in an AppVM, based on a TemplateVM. I have it in a StandaloneVM. Look at [Qubes docs](https://www.qubes-os.org/doc/software-update-vm/) for details.

**Comment by danielcapello** [comment]
@waiting-for-dev Thank you!

**Comment by isaacwagithub** [comment]
Hello. I have an issue.Im trying to deploy an app on heroku for the first time but everytime i try this on my console ''heroku git:remote -a project-name i get this output'' i get this output ''!    'ENOENT': spawn tasklist ENOENT.'' please help

**Comment by jdxcode** [comment]
@isaacwagithub are you on a windows machine that doesn't have `tasklist.exe`?

**Comment by darmoz** [comment]
Hi I have the same issue as @isaacwagithub . My windows has tasklist.exe at windows/system32. I tried to reinstall heroku and then I was able to use herooku -- version but after "heroku login" ENOENT is back.

**Comment by darmoz** [comment]
I fixed the problem with tasklist ENOENT. Heroku has to be run in my case in administrator mode. I had to run CMD as administrator then all works as it should.

**Comment by ManojKumarHC** [comment]
Hi even i had this issue from past 3 days . i was working in windows machine . when ever i need to deploy i was moving ubuntu machine  & deploying . i was not understanding what exactly the issue causing this . help me in resolving the issue in windows machine .

**Comment by nshettys** [comment]
Thanks darmoz. I had the same issue, and windows had tasklist.exe....but when I included my system32 folder in the path , heroku worked perfectly

**Comment by iamjosan** [comment]
@nshettys your solution worked for me as well. I'm on Windows 7.

**Comment by Kudratov** [comment]
@iamjosan 
PATH -> C:\Users\John\AppData\Roaming\npmv;C:\Program Files\MongoDB\Server\3.6\bin;C:\Program Files\Heroku\bin
not working)

**Comment by iamjosan** [comment]
@kudratov you didn't read the solution properly. Include the system32 *folder*: C:\Windows\System32

**Comment by Kudratov** [comment]
@iamjosan Thank you, bro

**Comment by isaacwagithub** [comment]
Hello. Thank you. I got it to work now. I was just missing a process file

On Tuesday, April 17, 2018, Kudratov <notifications@github.com> wrote:
> @iamjosan Thank you, bro
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/eEqosuVvVJcGEWVnYMAbrTMCE4oxIAGT89spPcrf4IenVu75vBx506CZF4EpGpOM-xFyat_lFvKvcbkco69QAdR_xE6Uk3nInJ-5MUZIcts_UYGCvMZbo_MNNpVRvWDE6CCIaph7r54s9m9dhD3QvqAjBkAcSQ=s0-d-e1-ft#https://github.com/notifications/beacon/AawcIp839nOuf3c8qut-IOZdqSzOJNnYks5tpa7XgaJpZM4Je7h6.gif>

**Comment by isaacwagithub** [comment]
Hello
I'd like some help with adding my bank card number so I can include
add-ons. I'm having trouble. My card gateway is blocked. Please help me out

On Friday, April 20, 2018, Isaac Mokoena <imokoena268@gmail.com> wrote:
> Hello. Thank you. I got it to work now. I was just missing a process file
>
> On Tuesday, April 17, 2018, Kudratov <notifications@github.com> wrote:
>> @iamjosan Thank you, bro
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/eEqosuVvVJcGEWVnYMAbrTMCE4oxIAGT89spPcrf4IenVu75vBx506CZF4EpGpOM-xFyat_lFvKvcbkco69QAdR_xE6Uk3nInJ-5MUZIcts_UYGCvMZbo_MNNpVRvWDE6CCIaph7r54s9m9dhD3QvqAjBkAcSQ=s0-d-e1-ft#https://github.com/notifications/beacon/AawcIp839nOuf3c8qut-IOZdqSzOJNnYks5tpa7XgaJpZM4Je7h6.gif>

**Comment by uhoh-itsmaciek** [comment]
@isaacwagithub sorry you're having trouble, but that doesn't have anything to do with the plugin. Please file a support ticket at help.heroku.com and we should be able to help.
