### ISSUE TITLE
Couldn't find that add-on

### ISSUE THREAD

**Issue by drmrbrewer** [heroku/heroku-pg-extras#134]
I install the plugin, apparently without issue:

    $ heroku plugins:install heroku-pg-extras
    Installing plugin heroku-pg-extras... done

But when I try to run one of the commands, I just get an error message:

    $ heroku pg:bloat
     ▸    Couldn't find that add-on.

I've tried the following variant, with the same result:

    $ heroku pg:bloat DATABASE_URL --app myapp
     ▸    Couldn't find that add-on.

And `DATABASE_URL` is populated OK with a `postgres://...` URL.

**Comment by keiko713** [comment]
Actually it's the same issue as https://github.com/heroku/heroku-pg/issues/16 (plus some other underlying sync issue inside of our internal systems), going to close this.

**Comment by dickeyxxx** [comment]
This is different. The database needs to be attached, you can't just set the config var like that.

**Comment by uhoh-itsmaciek** [comment]
Sure, but the error could be better =)

**Comment by keiko713** [comment]
Yeah, sorry my point is that the error is very confusing and that needs to be improved. Previously, we were at least saying "you meant BROWN?" something like that, which has been helping customers.
We'll need to look into the sync issue definitely (the database that is supposed to be attached is not attached in api side), but that's something we should track internally and separate it from CLI issue.

**Comment by dickeyxxx** [comment]
We're discussing in #ecosystem if you want to join. The bigger problem here is that it's too easy to get into a situation where you have DATABASE_URL not attached, which could cause bigger and less obvious problems down the road. Potentially we're saying maybe it would be good to show a warning on `heroku config:set` if the user sets something to a current addon config value.

**Comment by dickeyxxx** [comment]
@drmrbrewer is the database a heroku postgres database?

**Comment by drmrbrewer** [comment]
@dickeyxxx yes it is.

**Comment by dickeyxxx** [comment]
use `heroku pg:promote` to promote the db to DATABASE_URL

**Comment by keiko713** [comment]
@dickeyxxx sorry forgot to mention, but he opened up a ticket with us and we sorted this out there by using `pg:promote` method

**Comment by drmrbrewer** [comment]
Yep, would have been handy if the error message tells the user to try that, rather than the existing message.

**Comment by babaphemy** [comment]
hi I used pg:promote but there is no colour in the database url = postgresql-contoured-39188 . Please advise on the new command. Thanks

**Comment by uhoh-itsmaciek** [comment]
@babaphemy I don't quite follow; can you clarify your issue?  What exact command did you run, what error did you get, and what output were you expecting?

**Comment by babaphemy** [comment]
Thanks uhoh-itsmaciek,
I got creating alphablog... after the command to add pg addons, I then typed heroku pg:promote alphablog and I goot add on not found.
Please what am I doing wrong?
Thanks

**Comment by uhoh-itsmaciek** [comment]
@babaphemy is `alphablog` the name of your app? Are you running the command in a directory with your heroku remote defined (you can check this via `git remote -v`)? Also, I'm not sure if it's relevant here, but the first `heroku-postgresql` add-on you create on an app will be automatically assigned to `DATABASE_URL` by default--there is no need to run `heroku pg:promote` unless you explicitly gave it another attachment name (or want to set another attached `heroku-postgresql` add-on as the primary database).

**Comment by babaphemy** [comment]
@uhoh-itsmaciek you are right no need to do pg promote. Its working fine now. I guess I was following a very old tutorial. Thanks
