### ISSUE TITLE
Explanation for pg:outliers headers

### ISSUE THREAD

**Issue by daemonsy** [heroku/heroku-pg-extras#142]
Hi Heroku, I've been a user of this command for the last 3 years. It's super useful to find expensive and abnormal queries by with high percentages in `prop_exec_time` and `ncalls`.

After reading an [article](https://schneems.com/2017/07/18/how-i-reduced-my-db-server-load-by-80/) by @schneems and reading this quote

> When I installed the extension and ran the command I found that one query accounted for a whopping (you guessed it) 80% of total execution time.

it dawned on me that I never tried to fully understand what those headers mean. If you google one of them, the first hit is a SO question that really isn't answered. 

https://stackoverflow.com/questions/34744792/what-are-the-time-columns-output-in-pgoutliers-and-pgcalls

I'm suggesting to add the exact definitions of the headers to the README, it will be useful for future users.

**Comment by mble** [comment]
https://github.com/heroku/heroku-pg-extras/pull/163 provides an explanation of these columns.
