### ISSUE TITLE
External DBs?

### ISSUE THREAD

**Issue by pachacamac** [heroku/heroku-pg-extras#144]
Is there any way to extend this so it works with remote databases that are not hosted on heroku?

**Comment by uhoh-itsmaciek** [comment]
As this is a Heroku CLI plugin, our primary focus is on making this work for the Heroku ecosystem. Can you tell us more about your use case?

**Comment by jdxcode** [comment]
it's open source code and mostly sql scripts, you can easily copy these scripts and run them manually https://github.com/heroku/heroku-pg-extras/blob/master/commands/long_running_queries.js#L10-L22

**Comment by pachacamac** [comment]
Thanks @jdxcode good point.

@uhoh-itsmaciek I have an app on Heroku which connects to a Postgres database on Amazon RDS.

**Comment by uhoh-itsmaciek** [comment]
Unfortunately, I don't think we see a compelling use case to support that configuration. As @jdxcode said, you can use the queries directly or fork the plugin to connect to an external DB (the changes you'd need to make would be small and mostly in the resolver, I think).
