### ISSUE TITLE
pg:locks doesn't consider about locks other than EXCLUSIVE

### ISSUE THREAD

**Issue by keiko713** [heroku/heroku-pg-extras#149]
We should at least add `ACCESS EXCLUSIVE`, and potentially adding other locks as well.
https://github.com/heroku/heroku-pg-extras/blob/07cda801f3368676afd54b6fee8b2874f3487701/commands/locks.js#L32

**Comment by mble** [comment]
I think we can expand this out to `AccessExclusiveLock`, `ExclusiveLock` and `RowExclusiveLock`, as they are the most likely conflicting locks.
