### ISSUE TITLE
pg:blocking query is old

### ISSUE THREAD

**Issue by keiko713** [heroku/heroku-pg-extras#150]
I believe that the query of `pg:blocking` came from following page (looking at https://github.com/heroku/heroku-pg-extras/issues/80):
https://wiki.postgresql.org/wiki/Lock_Monitoring

However, the query definitely changed. Looking at Japanese version of that page, the query is very similar to "if Postgres version is below 9.2", and Heroku Postgres doesn't have 9.2 anymore so we should update it to up-to-date one.
https://github.com/heroku/heroku-pg-extras/blob/07cda801f3368676afd54b6fee8b2874f3487701/commands/blocking.js#L8-L21

**Comment by chrismo** [comment]
Sad to see such an old issue for this. I'd love to see this fixed.
