### ISSUE TITLE
Unable to call pg:outliers even when pg_stat_statements is installed

### ISSUE THREAD

**Issue by henrytseng** [heroku/heroku-pg-extras#156]
A call to `heroku pg:outliers` return a warning:

```
 ▸    pg_stat_statements extension need to be installed in the public schema first.
 ▸    This extension is only available on Postgres versions 9.2 or greater. You can install it by running:
 ▸    
 ▸    CREATE EXTENSION pg_stat_statements;
```

But when I query the same database with `SELECT * FROM pg_available_extensions` it seems that `pg_stat_statements` is listed.

**Comment by uhoh-itsmaciek** [comment]
@henrytseng that view shows the [*available* extensions](https://www.postgresql.org/docs/current/static/view-pg-available-extensions.html). Does `pg_stat_statements` show up in `pg_extension`, which lists the installed extensions? If so, what schema is it installed in? Currently it must be installed in the public schema for `pg:outliers` to work.

**Comment by henrytseng** [comment]
It shows up and is installed in the public list.

**Comment by uhoh-itsmaciek** [comment]
@henrytseng what does `show search_path` show for your user?

**Comment by henrytseng** [comment]
It shows `"$user", public`

**Comment by uhoh-itsmaciek** [comment]
@henrytseng okay, that looks right, but I think this must be something specific to your database or your setup. Can you file a ticket at https://help.heroku.com please?
