### ISSUE TITLE
Error: no such option: -c

### ISSUE THREAD

**Issue by hammady** [heroku/heroku-pg-extras#169]
Whenever I run any command, I get the following error:
`Error: no such option: -c`

```
$ heroku version
heroku-toolbelt/3.43.9999 (x86_64-darwin10.8.0) ruby/1.9.3
heroku/7.12.3 darwin-x64 node-v10.9.0

$ heroku plugins:install heroku-pg-extras
Installing plugin heroku-pg-extras... installed v1.1.6

$ heroku pg:bloat -a rayyan-qcri
Error: no such option: -c
```

**Comment by uhoh-itsmaciek** [comment]
Hi, it looks like you still have the old Ruby Heroku Toolbelt installed (in addition to the current node Heroku CLI) and it's causing these issues. See the instructions [here](https://github.com/heroku/cli/issues/709#issuecomment-371897254) for removing that; if that does not work, please file a ticket at https://help.heroku.com .
