### ISSUE TITLE
heroku login error 

### ISSUE THREAD

**Issue by mahraayush4321** [heroku/heroku-pg-extras#190]
Error: spawn cmd ENOENT
    Code: ENOENT
 »   Warning: Cannot open browser.
heroku: Waiting for login... /
i am getting this error when i am using heroku login

**Comment by iriberri** [comment]
Hi @mahraayush4321 - I'm sorry for the long delay in our response here.

The login functionality is part of the core Heroku CLI. If you're still seeing any related issues, would you mind reopening this issue in the https://github.com/heroku/cli repo?

Thank you!
