### ISSUE TITLE
Can't connect to db

### ISSUE THREAD

**Issue by kiskoza** [heroku/heroku-pg-extras#194]
Hi. I'm sure that I'm just missing a simple step, but can't figure out the reason why I got this error message.

```bash
heroku --version
# heroku/7.68.3 linux-x64 node-v14.19.0

heroku plugins:inspect heroku-pg-extras
# version: 1.2.4
# tag: latest
# ...

heroku pg:ps --app <my App> -v
# psql: error: FATAL:  no pg_hba.conf entry for host "<my public IP>", user "<REDACTED>", database "<REDACTED>", no encryption
 # ▸    psql exited with code 2
```

Could you help me find out what's missing?

**Comment by binarycleric** [comment]
Please reach out to support for connection issues: https://www.heroku.com/support.
Issues are only for reporting bugs within `heroku-pg-extras` itself.
