### ISSUE TITLE
Error on pg:vacuum_stats - "psql: server does not support SSL, but SSL was required"

### ISSUE THREAD

**Issue by mike-lang** [heroku/heroku-pg-extras#35]
I get the error "psql: server does not support SSL, but SSL was required" when I try to run the pg:vacuum_stats command on my database.  I'm running postgreSQL 9.2, and I've installed postgreSQL 9.2 on my x64 Windows 7 machine.  Other commands, such as pg:bloat and pg:long_running_queries work as desired

**Comment by eltmon** [comment]
I am getting this issue as well.
DL is deprecated, please use Fiddle
psql: server does not support SSL, but SSL was required
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       psql failed. exit status 512, output: "" (RuntimeError)
    Command:     heroku pg:vacuum-stats
    Plugins:     heroku-pg-extras
    Version:     heroku/toolbelt/3.43.5 (i386-mingw32) ruby/2.1.7
    Error ID:    8ffea0890a8c493a856f751c051659c9

**Comment by uhoh-itsmaciek** [comment]
@eltmon What is the message `DL is deprecated, please use Fiddle` about? I'm assuming per the error message you're on Windows? What version of Windows?

**Comment by simonneutert** [comment]
I am running Mac OS X 10.12.5 and get this error:
`psql: sslmode value "require" invalid when SSL support is not compiled in`

`gem uninstall pg` and reinstall didn't help. Had the newest versions of postgresql from homebrew installed.

**Comment by uhoh-itsmaciek** [comment]
@simonneutert it sounds like that might be a different error--your client may not support SSL. Can you paste the output of ` pg_config --libs --configure`?

**Comment by simonneutert** [comment]
sure, @uhoh-itsmaciek here it is:
```
-lpgcommon -lpgport -lz -lreadline -lm  
'--prefix=/Users/simonneutert/.asdf/installs/postgres/9.6.1'
```

**Comment by uhoh-itsmaciek** [comment]
@simonneutert yeah, so it looks like SSL support was not linked in to your build. Check out mine:

>maciek@mothra:~$ pg_config --libs --configure
>-lpgcommon -lpgport -lselinux -lxslt -lxml2 -lpam **-lssl** -lcrypto -lgssapi_krb5 -lz -ledit -lrt -lcrypt -ldl -lm  
>'--with-tcl' '--with-perl' '--with-python' '--with-pam' **'--with-openssl'** '--with-libxml' '--with-libxslt' ...

(emphasis added and some configure opts elided)

I'm not sure how to set up a Postgres with SSL from homebrew (I'm on Ubuntu), but I'm pretty sure it's possible. Alternately, there's also [Postgres.app](https://postgresapp.com/)...

**Comment by simonneutert** [comment]
@uhoh-itsmaciek this addon works with homebrew version of postgres, I had to clean up what asdf left and reinstall pg gem one last time.
What `pg_config --libs --configure` spits out looks much more similar to yours now. 

Thank you so much for your support, have a nice weekend!

**Comment by uhoh-itsmaciek** [comment]
Nice, glad to hear it. Happy to help.
