### ISSUE TITLE
Add command for which shows what pg:cache-hit show for each table?

### ISSUE THREAD

**Issue by PikachuEXE** [heroku/heroku-pg-extras#75]
I modified this code:

``` sql
SELECT
    relname,
    heap_blks_hit,
    heap_blks_read,
    heap_blks_hit + heap_blks_read AS total_read,
    heap_blks_hit / (heap_blks_hit + heap_blks_read + 1)::float AS ratio 
FROM pg_statio_user_tables
ORDER BY ratio DESC;
```

I was checking the cache rate in staging and production.
The ratios seem so different so I decide to get the ratio for every table to find out what's not cached.
It's easier to understand after reading the actual read & hit numbers separated by tables.

**Comment by uhoh-itsmaciek** [comment]
Sorry this got lost. I think it makes sense--if you can port it to the [JavaScript plugin format](https://devcenter.heroku.com/articles/developing-cli-plugins), I'd like to merge it.
