### ISSUE TITLE
command pg:bloat fails (on windows)

### ISSUE THREAD

**Issue by primalr** [heroku/heroku-pg-extras#78]
```
ERROR:  syntax error at or near ";"
RAD 3:           SELECT current_setting('block_size');numeric AS bs...
```

**Comment by arunbhat** [comment]
I still have the same issue in windows. I get this error "could not find a "psql" to execute". I even reinstalled both heroku and postgres on paths that don't have a space in them.  Any help is much appreciated.

**Comment by dickeyxxx** [comment]
does `psql` work?

**Comment by arunbhat** [comment]
Yes psql works. I have been copy pasting the queries from bloat.js, index_usage.js to psql to get the statistics.

**Comment by arunbhat** [comment]
in fact pg:psql works

**Comment by uhoh-itsmaciek** [comment]
@arunbhat can you post the full error you are getting now? And the output of `heroku version`?

**Comment by arunbhat** [comment]
Here you go:

C:\Users\abhat>heroku pg:bloat database --app revvy-gpm-sandbox
could not find a "psql" to execute

C:\Users\abhat>heroku version
heroku/toolbelt/3.43.9 (i386-mingw32) ruby/2.1.7
heroku-cli/5.2.34-65b16c9 (windows-386) go1.6.2
=== Installed Plugins
heroku-pg-extras@1.0.5

**Comment by dickeyxxx** [comment]
I didn't test, but I think this will fix it https://github.com/heroku/heroku-pg/pull/13
